### PR TITLE
Newsletter block

### PR DESCRIPTION
**Pull request by picocodes**
I created a new Newsletter block. A user can add a new block by selecting MailOptin from the list of blocks. The user can then select a form from the block settings on the sidebar and it will automatically appear in the post/page.

### CODE REVIEW

**Comment by collizo4sky** [comment]
@picocodes great job. Could you please include a feature where if no sidebar/widget or inpost form are created or not activate, a notice is displayed. For example, it will be something like "you currently have no inpost or sidebar/widget optin created or activated"

**Comment by collizo4sky** [comment]
@picocodes there is no visual representation that the block has been embedded.

**Comment by picocodes** [comment]
> @picocodes there is no visual representation that the block has been embedded.

Can you please elaborate further. The newsletter form appears in the post editor. Or do you want me to add something like a toast, that says the block has been added into the post?

**Comment by picocodes** [comment]
@collizo4sky I have edited the block to:

- Display a notice asking the user to create a new optin form. Since the notice can't be displayed on the sidebar, It will be displayed in the post, right where a block would have appeared.
- If the user has activated a block, the first block will be rendered in the post edit screen. The user can then select any other block from the sidebar and it will automatically replace the one in the post edit screen.

**Comment by collizo4sky** [comment]
@picocodes I am on latest wordpress version. The form is not showing on the post edit screen. But it does shows up on the frontend.

image

On reloading the edit screen, I got these errors

image

It appears this only happens for "inpost forms" but sidebar/widget forms work perfectly.

**Comment by collizo4sky** [comment]
@picocodes 

> the errors are displayed every time you edit a block's render function. That won't be a problem after we make all the requested changes since we won't have to edit the render function ever again.

Not sure I understand what render function in this context means. Could you please explain like I am 5 😆 

I created another letterbox optin and it worked correctly. Really do not know why the earlier one didn't work  and it's still not working. and the weird thing is, no error in console.

**Comment by mutendebrian** [comment]
Sorry, I meant the save function.

**Pull request merged**
