### PR TITLE
Custom field types

### PR DESCRIPTION
**Pull request by picocodes**
@collizo4sky  This is ready for a test drive. Quick question, do we style the new fields using style attributes or will we modify the optin themes to add styles for the new fields? I'm guessing we can style using style attributes and then we only modify the themes where our styles will look off.

### CODE REVIEW

**Comment by collizo4sky** [comment]
@picocodes you can do that here https://github.com/mailoptin/core/blob/master/src/OptinForms/AbstractOptinForm.php#L522

**Comment by picocodes** [comment]
Issa good thing that we can change themes directly from the customizer without having to create a new form.

**Comment by collizo4sky** [comment]
@picocodes i made some more styling changes.

> We will also have to review all optin themes to ensure they beautifully/correctly display the newly added custom fields. Please do this too.

I thought I would be able to go over this myself. Please do it.

**Comment by collizo4sky** [comment]
@picocodes I am tired of checking. I trust you did your due diligence. So I'll be merging

**Comment by picocodes** [comment]
Yeah :smile:

**Pull request merged**
